#!/usr/bin/env bash

# Retry a command with exponential backoff
function retry {
  local maxAttempts=$1
  local secondsDelay=1
  local attemptCount=1
  shift 1

  local status
  local command="${@}"

  while [[ $attemptCount -le $maxAttempts ]]; do
    bash -c "${command}" || status=$?

    if [[ $status -eq 0 ]]; then
      break
    fi

    if [[ $attemptCount -lt $maxAttempts ]]; then
      echo "Command [$@] failed after attempt $attemptCount of $maxAttempts. Retrying in $secondsDelay second(s)." >&2

      sleep $secondsDelay
    elif [[ $attemptCount -eq $maxAttempts ]]; then
      echo "Command [$@] failed after $attemptCount attempt(s)" >&2

      return $status
    fi

    attemptCount=$((attemptCount + 1))
    secondsDelay=$((secondsDelay * 2))
  done
}

retry "${@}"
