#!/usr/bin/env bash
# @import lang/truth
# @import console/info

main ()
{
    verbose true
    strict true

    if _ truth "$DOCKER"; then
        _ info "Copying build artifacts ..."

        [ -d /artifacts/RPMS ] && cp -rf /artifacts/RPMS /host/
        [ -d /artifacts/SRPMS ] && cp -rf /artifacts/SRPMS /host/
    fi

}
