#!/usr/bin/env bash
# @description build RPM
# @import lang/exists
# @import lang/first
# @import console/die
# @import rpmbuild/rpmbuild

main ()
{
    verbose true
    strict true

    TEST_SUITE="$(_ first "${TEST_SUITE}" "$1")" || _ die "No test suite chosen"

    if _ exists selinuxenabled
    then
        selinuxenabled && chcon -Rt svirt_sandbox_file_t "${MANAGE_REPOSITORY}"
    fi

    _ rpmbuild "${TEST_SUITE}"
}
