#!/usr/bin/env bash
# @description build RPM
# @import lang/exists
# @import lang/first
# @import console/die
# @import rpmbuild/rpmbuild

main ()
{
    verbose true
    strict true

    if _ exists selinuxenabled
    then
        selinuxenabled && sudo chcon -Rt svirt_sandbox_file_t "${MANAGE_REPOSITORY}"
    fi

    for spec in "$@"
    do
        _ rpmbuild "${spec}"
    done

    # while read -d '' -r dir
    # do
    #     sudo chown "${USER}:${GROUP}" "${dir}" >& /dev/null || true
    # done < <(find "${MANAGE_REPOSITORY}/SRPMS" "${MANAGE_REPOSITORY}/RPMS" -type d -print0 2> /dev/null)
    #
    # while read -d '' -r file
    # do
    #     if [[ "${file##*.}" == "rpm" ]]
    #     then
    #         sudo chown "${USER}:${GROUP}" "${file}" >& /dev/null || true
    #     fi
    # done < <(find "${MANAGE_REPOSITORY}/SRPMS" "${MANAGE_REPOSITORY}/RPMS" -type f -print0 2> /dev/null)
}
