name: container
on:
  # schedule:
  #   - cron: '10 16 * * 2'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  container:
    runs-on: ubuntu-latest
    concurrency: container
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          lfs: true
          submodules: true
      - name: docker login
        uses: docker/login-action@v3
        with:
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          username: ${{ github.actor }}
      - name: setup qemu
        uses: docker/setup-qemu-action@v3
      - name: docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: container metadata
        id: container-metadata
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: index
        uses: docker/metadata-action@v5
        with:
          flavor: |
            latest=false
            prefix=
            suffix=
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=schedule,pattern={{date 'YYYYMMDD'}}
            type=sha
            type=raw,value=latest,enable=true
      - name: build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: ${{ steps.container-metadata.outputs.tags }}
          labels: ${{ steps.container-metadata.outputs.labels }}
          annotations: ${{ steps.container-metadata.outputs.annotations }}
