name: release
on:
  workflow_dispatch:

jobs:
  release:
    concurrency: release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          lfs: true
          submodules: true
      - name: docker login
        uses: docker/login-action@v3
        with:
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          username: ${{ github.actor }}
      - name: install rpmsign
        run: sudo apt-get install -y rpm
      - name: configure gpg key
        run: echo "$PGP_PRIVATE_KEY_SECURITY" | gpg --import
        env:
          PGP_PRIVATE_KEY_SECURITY: ${{ secrets.PGP_PRIVATE_KEY_SECURITY }}
      - name: sign rpms
        run: rpmsign --addsign --key-id=security@escapace.com RPMS/*.rpm SRPMS/*.rpm
      - name: download repository
        run: aws s3 sync "s3://releases" repository
        env:
          AWS_ENDPOINT_URL: ${{ secrets.AWS_ENDPOINT_URL }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: auto
          AWS_EC2_METADATA_DISABLED: true
      - name: update repository
        run: ./manage update-repository
      - name: upload repository
        run: aws s3 sync repository "s3://releases"
        env:
          AWS_ENDPOINT_URL: ${{ secrets.AWS_ENDPOINT_URL }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: auto
          AWS_EC2_METADATA_DISABLED: true
