name: release
on:
  push:
    branches:
      - trunk
    paths:
      - "RPMS/**"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  release:
    concurrency: release
    runs-on: ubuntu-latest
    steps:
      - name: apparmor
        run: |
          sudo sysctl -w kernel.apparmor_restrict_unprivileged_unconfined=0
          sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
          # https://github.com/actions/runner-images/issues/10015#issuecomment-2668163375
          sudo systemctl disable --now apparmor.service
          sudo aa-teardown || true
      - name: checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          lfs: true
          submodules: true
      - name: install rpmsign
        run: sudo apt-get install -y rpm
      - name: configure gpg key
        run: echo "$PGP_PRIVATE_KEY_SECURITY" | gpg --import
        env:
          PGP_PRIVATE_KEY_SECURITY: ${{ secrets.PGP_PRIVATE_KEY_SECURITY }}
      - name: sign rpms
        run: rpmsign --addsign --key-id=security@escapace.com RPMS/*.rpm SRPMS/*.rpm
      - name: download repository
        run: aws s3 sync "s3://releases" repository
        env:
          AWS_ENDPOINT_URL: ${{ secrets.AWS_ENDPOINT_URL }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: auto
          AWS_EC2_METADATA_DISABLED: true
      - name: update repository
        run: ./manage update-repository
      - name: upload repository
        run: |
          aws configure set default.s3.max_concurrent_requests 2
          aws configure set default.s3.multipart_threshold "50MB"
          aws s3 sync --checksum-algorithm CRC32 repository "s3://releases"
        env:
          AWS_ENDPOINT_URL: ${{ secrets.AWS_ENDPOINT_URL }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: auto
          AWS_EC2_METADATA_DISABLED: true
